#!/usr/bin/env bash
# Report DNS posture for the sender domain configured in fnox. Pure
# observation -- doesn't mutate anything. Used by `mise run email:dns:check`.
#
# Reads CF_EMAIL_SENDER_DOMAIN from env (mise/fnox injects). Prints the
# current state of SPF, DMARC, and MX, plus the records Cloudflare expects
# to see for outbound send + inbound routing to work.
#
# DKIM records are generated by Cloudflare per-domain and not knowable
# without an API lookup; we point at the dashboard instead.

set -euo pipefail

domain="${CF_EMAIL_SENDER_DOMAIN:-}"
if [ -z "$domain" ]; then
  echo "CF_EMAIL_SENDER_DOMAIN is not set. Run:" >&2
  echo "  mise run email:worker:domain-set -- your-domain.example.com" >&2
  exit 1
fi

bold() { printf '\033[1m%s\033[0m\n' "$*"; }
dim()  { printf '\033[2m%s\033[0m\n' "$*"; }

bold "Sender domain: $domain"
echo

# ----------------------------------------------------------------------------
# SPF
# ----------------------------------------------------------------------------
bold "SPF (TXT $domain)"
spf=$(dig +short TXT "$domain" | tr -d '"' | grep -i '^v=spf' || true)
if [ -n "$spf" ]; then
  echo "  $spf"
  if echo "$spf" | grep -qi 'cloudflare'; then
    echo "  -> includes Cloudflare"
  else
    echo "  WARNING: SPF present but does NOT include Cloudflare."
  fi
else
  echo "  (no SPF record)"
fi
dim "  Recommended: v=spf1 include:_spf.mx.cloudflare.net ~all"
echo

# ----------------------------------------------------------------------------
# DMARC
# ----------------------------------------------------------------------------
bold "DMARC (TXT _dmarc.$domain)"
dmarc=$(dig +short TXT "_dmarc.$domain" | tr -d '"' | grep -i '^v=DMARC' || true)
if [ -n "$dmarc" ]; then
  echo "  $dmarc"
else
  echo "  (no DMARC record)"
  echo "  Note: inbound replies via InboundEmail::reply() require DMARC on"
  echo "        the SENDER's domain, not yours. Yours only matters for"
  echo "        downstream deliverability."
fi
dim "  Minimal monitoring config: v=DMARC1; p=none;"
echo

# ----------------------------------------------------------------------------
# MX (needed for inbound routing)
# ----------------------------------------------------------------------------
bold "MX ($domain)"
mx=$(dig +short MX "$domain" || true)
if [ -n "$mx" ]; then
  echo "$mx" | sed 's/^/  /'
  if echo "$mx" | grep -qi 'mx\.cloudflare\.net'; then
    echo "  -> routes through Cloudflare Email Routing"
  fi
else
  echo "  (no MX records -- inbound will not work)"
fi
dim "  Recommended for CF Email Routing:"
dim "    10 isaac.mx.cloudflare.net."
dim "    14 linda.mx.cloudflare.net."
dim "    20 amir.mx.cloudflare.net."
echo

# ----------------------------------------------------------------------------
# DKIM (CF-managed; just point at dashboard)
# ----------------------------------------------------------------------------
bold "DKIM"
echo "  Cloudflare Email Service generates DKIM records per-domain."
echo "  Manage at: https://dash.cloudflare.com -> Email -> Email Service ->"
echo "             Domains -> $domain"
echo "  (Records appear in the dashboard after you add the domain to Email"
echo "  Service. Add them to DNS via Cloudflare's auto-DNS or manually.)"
