#!/usr/bin/env nu
# Report DNS posture for the sender domain configured in fnox. Pure
# observation -- doesn't mutate anything. Used by `mise run email:dns:check`.
#
# Reads CF_EMAIL_SENDER_DOMAIN from env (mise/fnox injects). Prints the
# current state of SPF, DMARC, and MX, plus the records Cloudflare expects
# to see for outbound send + inbound routing to work.
#
# DKIM records are generated by Cloudflare per-domain and not knowable
# without an API lookup; we point at the dashboard instead.

def --env trim-quotes [] {
    $in | str trim --char '"'
}

def section [title: string] {
    print $"\n(ansi attr_bold)($title)(ansi reset)"
}

def dim [msg: string] {
    print $"  (ansi attr_dimmed)($msg)(ansi reset)"
}

def main [] {
    let domain = ($env.CF_EMAIL_SENDER_DOMAIN? | default "")
    if ($domain | is-empty) {
        print "CF_EMAIL_SENDER_DOMAIN is not set. Run:"
        print "  mise run email:worker:domain-set -- your-domain.example.com"
        exit 1
    }

    print $"Sender domain: (ansi attr_bold)($domain)(ansi reset)"

    # ------------------------------------------------------------------------
    # SPF
    # ------------------------------------------------------------------------
    section $"SPF \(TXT ($domain)\)"
    let spf = (
        ^dig +short TXT $domain
        | lines
        | each { trim-quotes }
        | where ($it | str downcase | str starts-with "v=spf")
    )
    if ($spf | is-empty) {
        print "  (no SPF record)"
    } else {
        for r in $spf {
            print $"  ($r)"
            if ($r | str downcase | str contains "cloudflare") {
                print "  -> includes Cloudflare"
            } else {
                print "  WARNING: SPF present but does NOT include Cloudflare."
            }
        }
    }
    dim "Recommended: v=spf1 include:_spf.mx.cloudflare.net ~all"

    # ------------------------------------------------------------------------
    # DMARC
    # ------------------------------------------------------------------------
    section $"DMARC \(TXT _dmarc.($domain)\)"
    let dmarc = (
        ^dig +short TXT $"_dmarc.($domain)"
        | lines
        | each { trim-quotes }
        | where ($it | str downcase | str starts-with "v=dmarc")
    )
    if ($dmarc | is-empty) {
        print "  (no DMARC record)"
        print "  Note: inbound replies via InboundEmail::reply() require DMARC on"
        print "        the SENDER's domain, not yours. Yours only matters for"
        print "        downstream deliverability."
    } else {
        for r in $dmarc { print $"  ($r)" }
    }
    dim "Minimal monitoring config: v=DMARC1; p=none;"

    # ------------------------------------------------------------------------
    # MX (needed for inbound routing)
    # ------------------------------------------------------------------------
    section $"MX \(($domain)\)"
    let mx = (
        ^dig +short MX $domain
        | lines
        | where ($it | str length) > 0
    )
    if ($mx | is-empty) {
        print "  (no MX records -- inbound will not work)"
    } else {
        for r in $mx { print $"  ($r)" }
        if ($mx | any { $in | str contains "mx.cloudflare.net" }) {
            print "  -> routes through Cloudflare Email Routing"
        }
    }
    dim "Recommended for CF Email Routing:"
    dim "  10 isaac.mx.cloudflare.net."
    dim "  14 linda.mx.cloudflare.net."
    dim "  20 amir.mx.cloudflare.net."

    # ------------------------------------------------------------------------
    # DKIM (CF-managed; just point at dashboard)
    # ------------------------------------------------------------------------
    section "DKIM"
    print "  Cloudflare Email Service generates DKIM records per-domain."
    print "  Manage at: https://dash.cloudflare.com -> Email -> Email Service ->"
    print $"             Domains -> ($domain)"
    print "  (Records appear in the dashboard after you add the domain to Email"
    print "  Service. Add them to DNS via Cloudflare's auto-DNS or manually.)"
}
