name: Build MUSL Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build MUSL Binary
    runs-on: ubuntu-latest
    container:
      image: rust:alpine

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add --no-cache musl-dev openssl-dev openssl-libs-static

      - name: Build binary
        env:
          OPENSSL_STATIC: true
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary-musl
          path: target/x86_64-unknown-linux-musl/release/*
          if-no-files-found: error
