name: release-binaries

on:
  push: {}

permissions:
  contents: write

jobs:
  build:
    name: Build & Release Binaries
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Boot the Dagger Engine inside the runner, pinned to 0.18.10
      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # 2.5) Pre-pull Dagger engine image to avoid registry issues
      - name: Pre-pull Dagger Engine
        run: |
          echo "Pre-pulling Dagger engine image..."
          docker pull registry.dagger.io/engine:v0.18.10 || {
            echo "Failed to pull engine image, retrying..."
            sleep 5
            docker pull registry.dagger.io/engine:v0.18.10
          }

      # 3) Build all binaries with Dagger
      - name: Build All Binaries
        env:
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        run: |
          dagger -c 'build-all $(upload ".") | export ./artifacts'

      # 3.5) Debug: List artifacts directory
      - name: List Artifacts
        run: |
          echo "Contents of current directory:"
          ls -la
          echo "Contents of artifacts directory:"
          ls -la ./artifacts/ || echo "artifacts directory doesn't exist"
          find . -name "*.tar.gz" || echo "No tar.gz files found"

      # 4) Create timestamped pre-release
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          timestamp=$(date '+%Y-%m-%d-%H-%M-%S')
          tag_name="experiment-${timestamp}"
          
          gh release create "${tag_name}" \
            --title "Experiment Release ${timestamp}" \
            --notes "Automated experiment build from commit ${{ github.sha }}" \
            --prerelease \
            ./artifacts
