name: release-binaries

on:
  push: {}

jobs:
  hello:
    name: Hello Dagger
    runs-on: ubuntu-latest

    steps:
      # 1) Boot the Dagger Engine inside the runner, pinned to v0.18.10
      - name: Setup Dagger
        uses: dagger/dagger-for-github@v8.0.0
        with:
          version: "0.18.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # 2) Run a tiny Alpine container and print "Hello, World"
      - name: Hello from Alpine
        shell: dagger {0}
        run: |
          container | from alpine
            | with-new-file /hello.txt "Hello, World"
            | with-exec cat /hello.txt
            | stdout
