name: release-binaries

on:
  push: {}            # run on every branch/tag push so you can test before merging to main

permissions:
  contents: write      # required for gh release

jobs:
  #-----------------------------------------------------------
  # 1. Build matrix – each row runs on its own VM
  #-----------------------------------------------------------
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: darwin-arm64
            dagger_fn: darwin-build
            artifact: http-nu-darwin-arm64.tar.gz

          - target: windows-amd64
            dagger_fn: windows-build
            artifact: http-nu-windows-amd64.tar.gz

          - target: linux-arm64
            dagger_fn: linux-arm-64-build
            artifact: http-nu-linux-arm64.tar.gz

          - target: linux-amd64
            dagger_fn: linux-amd-64-build
            artifact: http-nu-linux-amd64.tar.gz

    steps:
      # 1) Check out source
      - uses: actions/checkout@v4

      # 2) Cache Dagger BuildKit cache (restore and save)
      - name: Cache Dagger
        uses: actions/cache@v4
        with:
          path: ~/.cache/dagger
          key: dagger-${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            dagger-${{ runner.os }}-${{ matrix.target }}-

      # 3) Boot the Dagger engine
      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # 4) Defensive: pre‑pull the engine image
      - name: Pre‑pull Dagger Engine
        run: docker pull registry.dagger.io/engine:v0.18.10

      # 5) Run one Dagger build function and export artefact
      - name: Build with Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "0.18.10"
          call: ${{ matrix.dagger_fn }} --src upload --src . export --path ./artifacts/${{ matrix.artifact }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      # 6) Upload artefact for fan‑in job
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ./artifacts/${{ matrix.artifact }}

  #-----------------------------------------------------------
  # 2. Fan‑in job – gather artefacts and create prerelease
  #-----------------------------------------------------------
  release:
    name: Create prerelease
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create GitHub prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          timestamp=$(date '+%Y-%m-%d-%H-%M-%S')
          tag="experiment-${timestamp}"

          # List files for log visibility
          find artifacts -type f -print

          gh release create "$tag" \
            --title "Experiment Release $timestamp" \
            --notes "Automated experiment build from commit ${{ github.sha }}" \
            --prerelease \
            artifacts/*
